### ISSUE TITLE
Implement PSR-3 for LoggerInterface

### ISSUE THREAD

**Issue by dpauli** [laminas/laminas-log#10]
Hey,

is there any information or discussion about implementing the PSR-3 standard for Logger (https://github.com/php-fig/log). We often have this problem (like using also Monolog Logger).

If not we will laminas-log and replace it with another framework.

Best regards, David

**Comment by michalbundyra** [comment]
@dpauli Have you seen the docs?
https://docs.laminas.dev/laminas-log/psr3/

**Comment by aurUpdates** [comment]
Ah, thx :-) Now I'm satisfied.

**Comment by dpauli** [comment]
Ah, thx :-) Now I'm satisfied.

**Comment by dpauli** [comment]
Okay, working with this solution causing the problem, that every usable `Writer` (like `Noop` or `Stream`) from Laminas not using the PSR-3 standard.

Is there a plan to change this, next major sounds nice? Or doublicating the given `Writer`s for PSR usage?

**Comment by weierophinney** [comment]
The writers will work fine with PSR-3, assuming you use the PsrLoggerAdapter, which requires you to configure the logger and its writers slightly differently: see https://docs.laminas.dev/laminas-log/service-manager/#psrloggerabstractservicefactory (which was linked to from the page we linked  you to originally).

Can you demonstrate what you have tried? It's likely a configuration issue, but we need to know what you're doing so that we can attempt to reproduce and either point out the correct configuration, or determine that there is a bug.

**Comment by dpauli** [comment]
Perhaps I see it wrong, or does not get it:

The not-PSR3 `Logger` adds the `Writter` (https://github.com/laminas/laminas-log/blob/master/src/Logger.php#L273).
The PSR3 `Logger` will be added by the PSR3 ready `Writter` (see https://github.com/laminas/laminas-log/blob/master/src/Writer/Psr.php#L64).

If I use the PSR3 `Logger` it can not be added by the old `Writter`. All `Writer` implementation in laminas-log are instances of the old `Writter` and cannot add the `Logger`.

**Comment by Xerkus** [comment]
@dpauli This library predates PSR Logger and was a direct influence over it. It means that laminas-logger is pretty close but slightly incompatible. PSR decorators were enough and difference did not warrant  backwards incompatible change for existing users. 

If you would like to handle the _major_ undertaking preparing laminas-log 3.0.0 by bring it in line with PSR-3 and current Laminas code quality standards, we will be happy to provide guidance and assistance.

**Comment by Xerkus** [comment]
> If I use the PSR3 `Logger` it can not be added by the old `Writter`. All `Writer` implementation in laminas-log are instances of the old `Writer` and cannot add the `Logger`

I did not understand that part. Writers are not part of PSR-3, they are library internal detail.
When you want to use laminas-logger as a PSR-3 logger you would decorate it with `Laminas\Log\PsrLoggerAdapter`; when you want laminas-logger to write messages to another PSR-3 logger you would use `Psr` writer.

**Comment by dpauli** [comment]
Thats I wanna say :) There is a interface of a PSR-3 Writer (`Wrter\Psr`) but no ready implementation in `laminas-logger`. All existing Writer (like `Writer\Stream`) are not PSR-3 ready and does not implement the `Writer\Psr` interface.

Therefore my question:

When `laminas-logger` will have implementation of `Writer\Psr`?

**Comment by Xerkus** [comment]
@dpauli I would suggest to move this topic to the forums as it is a support kind. https://discourse.laminas.dev/c/questions/components/6
