### ISSUE TITLE
Not able to udpate laminas-log to version 2.13.1

### ISSUE THREAD

**Issue by dhananjay5358** [laminas/laminas-log#32]
Hi Team,

not able to update laminas-log version from 2.12.1 to 2.13.1.

Current version is 2.12.1

and while update using composer I am seeing message "nothing to install or update"

My Current php version 7.4.18 

Could you please let know If I am doing anything wrong ?

**Comment by Ocramius** [comment]
Try using `composer why-not`

**Comment by dhananjay5358** [comment]
When I tried composer why not laminas log 2.13.1

laminas/laminas-log                2.13.1    requires          laminas/laminas-servicemanager (^3.3.0)
magento/project-community-edition  2.4.2-p1  does not require  laminas/laminas-servicemanager (but 2.7.11 is installed)

it shows me above response and also I am not able to update module lamias-servicemanager liabrary also.

Note : My Magento Version is 2.4.2 p1.

**Comment by Ocramius** [comment]
Right, so it's not a bug with this library, but just a dependency graph issue with magento :)

I suggest you keep investigating with `composer why-not` for each dependency that is affected, but in general, your dependency graph dictates what is or isn't installable: it's not a bug in the libraries.
