### ISSUE TITLE
Error on build deploy for docs: The unauthenticated git protocol on port 9418 is no longer supported.

### ISSUE THREAD

**Issue by froschdesign** [laminas/laminas-log#35]
https://github.com/laminas/laminas-log/runs/6223336132?check_suite_focus=true#step:3:11

@weierophinney or @Xerkus can you help here?
Thanks in advance!

**Comment by Xerkus** [comment]
Checking.
We had this elsewhere already, iirc. I don't remember what it was. Something is pulling deps via `git://` url instead of `https://`?

**Comment by Xerkus** [comment]
This is due to the removal of deprecated feature by GitHub and it affects all our repositories using documentation build action, opened issue at https://github.com/laminas/documentation-theme/issues/80

**Comment by Xerkus** [comment]
Fixed in upstream
