### ISSUE TITLE
Cannot install package on a clean mezzio skeleton project

### ISSUE THREAD

**Issue by dansol** [laminas/laminas-log#48]
### Bug Report

|    Q            |   A
|------------ | ------
| PHP           | 8.1
| Composer | 2.4.4

#### Summary

Cannot install package on a clean mezzio skeleton installation
![laminas-log](https://user-images.githubusercontent.com/3524858/209391629-2931b78b-6c40-4cb8-823b-46c9d65f9c4b.png)

#### Current behavior
composer shows "Your requirements could not be resolved to an installable set of packages." after command 
composer require laminas/laminas-log

#### How to reproduce

create a fresh mezzio skeleton installation
then run 
composer require laminas/laminas-log

#### Expected behavior
laminas-log installed

**Comment by froschdesign** [comment]
@dansol 
[filp/whoops](http://filp.github.io/whoops/) requires the [PSR-3](https://www.php-fig.org/psr/psr-3/) logger interface with version 3 for PHP 8, but laminas-log is based on version 1 of PSR-3 logger interface.

Maybe the following package is an alternative for you: https://github.com/geo6/mezzio-monolog
