### ISSUE TITLE
Incorrect minimum version for PHP or wrong dependency for laminas/laminas-zendframework-bridge

### ISSUE THREAD

**Issue by sumariva** [laminas/laminas-log#49]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.5.1

#### Summary

I checked the packagist for the right version to use on my environment, a server with PHP 5.4.x.
According to the package list for laminas-laminas-log, version 2.5.1 should be compatible with PHP 5.4.
It states that the minimum version should be PHP: >=5.3.23.

But when targeting the project to use a PHP 5.4 environment, it causes a dependency unsatisfiable.
The problem is the dependency laminas/laminas-zendframework-bridge ^1.0, that requires PHP 5.6.
So, this dependency is wrong or the laminas-log minimum requirements are incorrect.
#### Current behavior

When executing the composer -W update command, it reports requirements not satisfiable.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laminas/laminas-zendframework-bridge[1.0.0, ..., 1.0.4] require php ^5.6 || ^7.0 -> your php version (5.4; overridden via config.platform, actual: 7.2.26) does not satisfy that requirement.
    - laminas/laminas-zendframework-bridge[1.1.0, ..., 1.1.1] require php ^5.6 || ^7.0 || ^8.0 -> your php version (5.4; overridden via config.platform, actual: 7.2.26) does not satisfy that requirement.
    - laminas/laminas-zendframework-bridge[1.2.0, ..., 1.3.0] require php ^7.3 || ^8.0 -> your php version (5.4; overridden via config.platform, actual: 7.2.26) does not satisfy that requirement.
    - laminas/laminas-zendframework-bridge[1.4.0, ..., 1.4.1] require php ^7.3 || ~8.0.0 || ~8.1.0 -> your php version (5.4; overridden via config.platform, actual: 7.2.26) does not satisfy that requirement.
    - laminas/laminas-zendframework-bridge[1.5.0, ..., 1.6.1] require php >=7.4, <8.2 -> your php version (5.4; overridden via config.platform, actual: 7.2.26) does not satisfy that requirement.
    - laminas/laminas-zendframework-bridge 1.7.0 requires php ~8.0.0 || ~8.1.0 || ~8.2.0 -> your php version (5.4; overridden via config.platform, actual: 7.2.26) does not satisfy that requirement.
    - laminas/laminas-log 2.5.1 requires laminas/laminas-zendframework-bridge ^1.0 -> satisfiable by laminas/laminas-zendframework-bridge[1.0.0, ..., 1.7.0].
    - Root composer.json requires laminas/laminas-log 2.5.1 -> satisfiable by laminas/laminas-log[2.5.1].
#### Expected behavior
Expected that composer could find a set of packages and update the project.

**Comment by Ocramius** [comment]
Sounds about right: using an older version would require `zendframework/zend-log`.

From our end, we don't patch for EOL'd PHP versions anyway, so you would need to move to PHP 8.0 or newer regardless.

**Comment by sumariva** [comment]
Ok, so the current solution is to replace the package.
I will check if the zendframework/zend-log has the PHP error handler, the feature that I mostly used for laminas-log.
I facing some bug on the application not been reported anywhere on server, and tried to add this logger to capture output.

**Comment by Ocramius** [comment]
If you added this package from scratch, perhaps consider using the more flexible `monolog/monolog`, which also comes with an error handler
