### ISSUE TITLE
Add support for psr/log 2.x and 3.x

### ISSUE THREAD

**Issue by InvisibleSmiley** [laminas/laminas-log#51]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no?

#### Summary

Add support for psr/log 2.x and 3.x.
It should be possible to keep support for psr/log 1.x.

**Comment by froschdesign** [comment]
@InvisibleSmiley 
See: https://github.com/laminas/laminas-log/issues/10
