### ISSUE TITLE
Deprection of E_STRICT in PHP 8.4

### ISSUE THREAD

**Issue by srjlewis** [laminas/laminas-log#57]
I have done some testing with PHP 8.4 and have seen to foollowing notice.

```PHP Deprecated:  Constant E_STRICT is deprecated in /project_dir/vendor/laminas/laminas-log/src/Logger.php on line 93```

**Comment by froschdesign** [comment]
I think the constant can be replaced with the concrete value (`2048`) and everything should work as before.

https://www.php.net/manual/errorfunc.constants.php#constant.e-strict
